### ISSUE TITLE
节点路径改变导致报错：ERROR: Service [/uav1/enable_motors] is not available.

### ISSUE THREAD

**Issue by Li-Jinjie** [smart-swarm/gazebo_drone_tutorials#1]
环境：Ubuntu 16.04 LTS，ROS-kinetic，gazebo7

你好，在按照[教程](https://zhuanlan.zhihu.com/p/106032638 )上的步骤在Ubuntu配置后，运行命令：`bashstart_test_uav1.sh`, 发现报错：_ERROR: Service [/uav1/enable_motors] is not available_.
查看rqt_graph如下：
![rosgraph](https://user-images.githubusercontent.com/45286479/74251350-f9026080-4d26-11ea-942b-1a75487f0980.png)
可知，所有节点的路径均变为/A/uav1/....
因此，将uav_arm.sh文件的语句从`rosservice call uav$i/enable_motors true`改为`rosservice call /A/uav$i/enable_motors true`后，运行成功。请问我该如何将所有路径前边的/A/去掉，以满足文件的默认路径呢？

**Comment by Li-Jinjie** [comment]
感觉整体很好，提出一小部分改进意见：1. 教程中

> 4.2 打开一个新终端：输入截图中命令（可用tab键补全字段）

部分的代码建议改为 
`rostopic pub -r 10 /uav1/pose_cmd geometry_msgs/Twist '{linear: {x: 10.0, y: 0.0, z: 10.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}'`
可能因为zsh的原因，那样换行输我敲了好几遍都不成功... 2. 最后的视频有一点点模糊，一些命令看不清楚。

**Comment by smart-swarm** [comment]
你用zsh 那就先不要敲 -r 10 把后面的都补全了再回来敲这个参数



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Li-Jinjie <notifications@github.com&gt;
发送时间: 2020年2月11日 23:50
收件人: smart-swarm/gazebo_drone_tutorials <gazebo_drone_tutorials@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[smart-swarm/gazebo_drone_tutorials] 节点路径改变导致报错：ERROR: Service [/uav1/enable_motors] is not available. (#1)




感觉整体很好，提出一小部分改进意见：1. 教程中
  
4.2 打开一个新终端：输入截图中命令（可用tab键补全字段）
  
部分的代码建议改为
 rostopic pub -r 10 /uav1/pose_cmd geometry_msgs/Twist '{linear: {x: 10.0, y: 0.0, z: 10.0}, angular: {x: 0.0, y: 0.0, z: 0.0}}'
 可能因为zsh的原因，那样换行输我敲了好几遍都不成功... 2. 最后的视频有一点点模糊，一些命令看不清楚。

**Comment by Li-Jinjie** [comment]
测试了一下新代码，没有这个问题了。
